// <auto-generated />
using System;
using Microdev.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Microdev.Infrastructure.Migrations
{
    [DbContext(typeof(MicrodevAppDbContext))]
    partial class MicrodevAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microdev.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Programming"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fasico"
                        },
                        new
                        {
                            Id = 3,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 4,
                            Name = "BFC"
                        });
                });

            modelBuilder.Entity("Microdev.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BossId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("Decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BossId = 2,
                            DepartmentId = 1,
                            FirstName = "Zahra",
                            LastName = "Bayat",
                            Salary = 2000m
                        },
                        new
                        {
                            Id = 2,
                            BossId = 1,
                            DepartmentId = 1,
                            FirstName = "Ali",
                            LastName = "Bayat",
                            Salary = 3000m
                        },
                        new
                        {
                            Id = 3,
                            BossId = 1,
                            DepartmentId = 1,
                            FirstName = "Sara",
                            LastName = "Masoodi",
                            Salary = 3000m
                        },
                        new
                        {
                            Id = 4,
                            BossId = 1,
                            DepartmentId = 1,
                            FirstName = "Mehdi",
                            LastName = "Mohamadi",
                            Salary = 3000m
                        },
                        new
                        {
                            Id = 5,
                            BossId = 1,
                            DepartmentId = 1,
                            FirstName = "Amin",
                            LastName = "Sadeghi",
                            Salary = 1000m
                        },
                        new
                        {
                            Id = 6,
                            BossId = 2,
                            DepartmentId = 1,
                            FirstName = "Shadi",
                            LastName = "Sohbati",
                            Salary = 1000m
                        },
                        new
                        {
                            Id = 7,
                            BossId = 2,
                            DepartmentId = 2,
                            FirstName = "Somaye",
                            LastName = "Mahdavi",
                            Salary = 1000m
                        },
                        new
                        {
                            Id = 8,
                            BossId = 2,
                            DepartmentId = 2,
                            FirstName = "Maryam",
                            LastName = "Zahedi",
                            Salary = 1000m
                        },
                        new
                        {
                            Id = 9,
                            BossId = 2,
                            DepartmentId = 2,
                            FirstName = "Mary",
                            LastName = "Zibayee",
                            Salary = 1000m
                        });
                });

            modelBuilder.Entity("Microdev.Domain.Entities.Employee", b =>
                {
                    b.HasOne("Microdev.Domain.Entities.Department", null)
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
